/**
* Generated by DeepSeek.
*/
#include <opencv2/opencv.hpp>
#include <opencv2/features2d.hpp>
#include <iostream>
#include <vector>

using namespace cv;
using namespace std;

// 函数：显示匹配结果（可选）
void ________showMatches111111111(const Mat& queryImg, const Mat& trainImg, const vector<Point2f>& queryCorners,
    const vector<Point2f>& trainCorners, const string& winName) {
    Mat outImg;
    drawMatches(queryImg, vector<KeyPoint>(), trainImg, vector<KeyPoint>(),
        vector<DMatch>(), outImg, Scalar::all(-1), Scalar::all(-1),
        vector<char>(), DrawMatchesFlags::NOT_DRAW_SINGLE_POINTS);
// 绘制投影的四边形
    for (int i = 0; i < 4; i++) {
        line(outImg, trainCorners[i] + Point2f(queryImg.cols * 1.0f, 0), trainCorners[(i + 1) % 4] + Point2f(queryImg.cols * 1.0f, 0),
            Scalar(0, 255, 0), 2);
    }
    imshow(winName, outImg);
    waitKey(0);
}

int ________main111(int argc, char** argv) {
    // 1. 加载原始图像列表（这里用vector存放）
    vector<Mat> originalImages;
    // 示例：加载多张图像，实际使用时请替换为真实路径
    originalImages.push_back(imread("original1.jpg"));
    originalImages.push_back(imread("original2.jpg"));
    // ... 添加更多图像

    // 2. 加载查询图像（从某张原始图像中截取并缩放得到的）
    Mat query = imread("query.jpg");
    if (query.empty()) {
        cerr << "无法加载查询图像" << endl;
        return -1;
    }

    // 3. 初始化ORB特征检测器和描述子提取器
    Ptr<ORB> orb = ORB::create(1000);  // 最多1000个特征点

    // 提取查询图像的特征
    vector<KeyPoint> keypointsQuery;
    Mat descriptorsQuery;
    orb->detectAndCompute(query, noArray(), keypointsQuery, descriptorsQuery);

    // 4. 创建BFMatcher（使用汉明距离，因为ORB描述子是二进制的）
    BFMatcher matcher(NORM_HAMMING);

    int bestImageIdx = -1;
    double bestScore = 0.0;
    vector<Point2f> bestCorners;

    // 5. 遍历每张原始图像，进行匹配
    for (size_t i = 0; i < originalImages.size(); ++i) {
        Mat trainImg = originalImages[i];
        if (trainImg.empty()) continue;

        // 提取训练图像特征
        vector<KeyPoint> keypointsTrain;
        Mat descriptorsTrain;
        orb->detectAndCompute(trainImg, noArray(), keypointsTrain, descriptorsTrain);

        // 匹配特征点
        vector<vector<DMatch>> knnMatches;
        matcher.knnMatch(descriptorsQuery, descriptorsTrain, knnMatches, 2);

        // Lowe's ratio test 筛选匹配点
        vector<DMatch> goodMatches;
        for (size_t j = 0; j < knnMatches.size(); ++j) {
            if (knnMatches[j][0].distance < 0.75 * knnMatches[j][1].distance) {
                goodMatches.push_back(knnMatches[j][0]);
            }
        }

        // 如果匹配点太少，跳过该图像
        if (goodMatches.size() < 10) continue;

        // 获取匹配点对坐标
        vector<Point2f> srcPoints, dstPoints;
        for (const auto& match : goodMatches) {
            srcPoints.push_back(keypointsQuery[match.queryIdx].pt);
            dstPoints.push_back(keypointsTrain[match.trainIdx].pt);
        }

        // 计算单应性矩阵（假设平面场景，且查询图像与目标区域为透视变换）
        Mat H = findHomography(srcPoints, dstPoints, RANSAC);

        // 如果单应性矩阵无效，跳过
        if (H.empty()) continue;

        // 将查询图像的四个角点投影到训练图像中
        vector<Point2f> queryCorners(4);
        queryCorners[0] = Point2f(0, 0);
        queryCorners[1] = Point2f((float)query.cols, 0);
        queryCorners[2] = Point2f((float)query.cols, (float)query.rows);
        queryCorners[3] = Point2f(0, (float)query.rows);

        vector<Point2f> trainCorners(4);
        perspectiveTransform(queryCorners, trainCorners, H);

        // 可选：验证投影区域是否合理（例如在图像边界内）
        bool valid = true;
        for (const auto& pt : trainCorners) {
            if (pt.x < 0 || pt.x >= trainImg.cols || pt.y < 0 || pt.y >= trainImg.rows) {
                valid = false;
                break;
            }
        }
        if (!valid) continue;

        // 计算匹配分数：可以用内点数量或投影误差等
        double score = (double)goodMatches.size() / keypointsQuery.size();  // 简单用匹配比例
        if (score > bestScore) {
            bestScore = score;
            bestImageIdx = (int)i;
            bestCorners = trainCorners;
        }

        // 可选：显示匹配结果
        // showMatches(query, trainImg, queryCorners, trainCorners, "Match Result");
    }

    // 6. 输出最佳匹配结果
    if (bestImageIdx >= 0) {
        cout << "匹配到的原始图像索引: " << bestImageIdx << endl;
        cout << "匹配区域角点 (在原始图像中):" << endl;
        for (const auto& pt : bestCorners) {
            cout << "  (" << pt.x << ", " << pt.y << ")" << endl;
        }
        // 可以绘制并显示结果
        Mat result = originalImages[bestImageIdx].clone();
        for (int i = 0; i < 4; i++) {
            line(result, bestCorners[i], bestCorners[(i + 1) % 4], Scalar(0, 255, 0), 2);
        }
        imshow("Best Match", result);
        waitKey(0);
    }
    else {
        cout << "未找到匹配" << endl;
    }

    return 0;
}